### PR TITLE
add link to atlrug CoC

### PR DESCRIPTION
**Pull request by KyFaSt**

### CODE REVIEW

**Comment by KyFaSt** [comment]
@vanstee I don't think this should break anything, if that's correct would you mind merging this?

**Comment by jasnow** [comment]
Checking it out - adding a line to cuke test.

**Comment by jasnow** [comment]
Been deployed - Unclear why on separate line.

**Comment by KyFaSt** [comment]
thanks @jasnow I'm not sure why either. I'm going to take a look at it though

**Comment by jasnow** [comment]
@KyFaSt - Fixed and deployed separate line issue. FYI.

**Pull request merged**
