### PR TITLE
WIP: Removes potentially unneeded migrate command

### PR DESCRIPTION
**Pull request by alindeman**

### CODE REVIEW

**Comment by alindeman** [comment]
@jasnow I wasn't able to reproduce the errors either, but I did see this line in .travis.yml that looked extraneous. I thought it was worth a try to remove it. Unfortunately I can't run the tests at all from a fork because there are secret values. Would you maybe like to pull it into a branch and see what happens?

**Comment by jasnow** [comment]
Here were some of my guesses:
 * Report TravisCI bug.
 * Report Rails arel/database bug.
 * Clean TravisCI bundler cache. (Tried deleted line in .travis.yml file/no help)
 * Fix before_script related to database.

**Comment by jasnow** [comment]
We got this:
```
Migrations are pending. To resolve this issue, run:
	bin/rails db:migrate RAILS_ENV=test
```

**Comment by alindeman** [comment]
Darn, I see the failure now. I've tried a new thought in #64. If that doesn't fix it, I think we'll need to dig deeper, agreed.

**Pull request merged**
